-- 0003 free and ultra low cost pricing columns plus discovery configuration.
-- Spec 0004 free and ultra low cost model ranking, child 0003 (AC-3, AC-10, AC-13).
--
-- offers gains typed price columns: normal and effective input, output, cache
-- read, cache write prices in USD per million tokens, source currency and
-- unit, USD conversion evidence, price source URL, price confirmation time,
-- and the discount period. Every numeric price is nullable with a check of
-- zero or greater (AC-3). Core prices never live in facts_json again.
--
-- discovery_sources, search_terms, and search_windows own the discovery
-- configuration that used to live in the tracked YAML files. The YAML content
-- is imported once with a stable migration marker (AC-13).

-- 1. offers price columns -----------------------------------------------------
ALTER TABLE offers ADD COLUMN normal_input_price_usd REAL CHECK (normal_input_price_usd IS NULL OR normal_input_price_usd >= 0);
ALTER TABLE offers ADD COLUMN normal_output_price_usd REAL CHECK (normal_output_price_usd IS NULL OR normal_output_price_usd >= 0);
ALTER TABLE offers ADD COLUMN normal_cache_read_price_usd REAL CHECK (normal_cache_read_price_usd IS NULL OR normal_cache_read_price_usd >= 0);
ALTER TABLE offers ADD COLUMN normal_cache_write_price_usd REAL CHECK (normal_cache_write_price_usd IS NULL OR normal_cache_write_price_usd >= 0);
ALTER TABLE offers ADD COLUMN effective_input_price_usd REAL CHECK (effective_input_price_usd IS NULL OR effective_input_price_usd >= 0);
ALTER TABLE offers ADD COLUMN effective_output_price_usd REAL CHECK (effective_output_price_usd IS NULL OR effective_output_price_usd >= 0);
ALTER TABLE offers ADD COLUMN effective_cache_read_price_usd REAL CHECK (effective_cache_read_price_usd IS NULL OR effective_cache_read_price_usd >= 0);
ALTER TABLE offers ADD COLUMN effective_cache_write_price_usd REAL CHECK (effective_cache_write_price_usd IS NULL OR effective_cache_write_price_usd >= 0);
ALTER TABLE offers ADD COLUMN source_amount_input REAL CHECK (source_amount_input IS NULL OR source_amount_input >= 0);
ALTER TABLE offers ADD COLUMN source_amount_output REAL CHECK (source_amount_output IS NULL OR source_amount_output >= 0);
ALTER TABLE offers ADD COLUMN source_currency TEXT;
ALTER TABLE offers ADD COLUMN source_unit TEXT;
ALTER TABLE offers ADD COLUMN conversion_rate REAL CHECK (conversion_rate IS NULL OR conversion_rate > 0);
ALTER TABLE offers ADD COLUMN conversion_source TEXT;
ALTER TABLE offers ADD COLUMN conversion_confirmed_at TEXT;
ALTER TABLE offers ADD COLUMN price_source_url TEXT;
ALTER TABLE offers ADD COLUMN price_verified_at TEXT;
ALTER TABLE offers ADD COLUMN discount_start_at TEXT;
ALTER TABLE offers ADD COLUMN discount_end_at TEXT;

-- 2. discovery_sources --------------------------------------------------------
CREATE TABLE discovery_sources (
  source_key TEXT PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('vendor', 'router', 'host', 'product', 'discovery', 'community', 'benchmark', 'watchlist', 'other')),
  label TEXT NOT NULL,
  source_url TEXT,
  parent_label TEXT,
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  priority INTEGER NOT NULL DEFAULT 100 CHECK (priority >= 0),
  added_from TEXT,
  created_at TEXT NOT NULL,
  last_attempted_at TEXT,
  last_success_at TEXT,
  consecutive_failures INTEGER NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0)
);
CREATE INDEX idx_discovery_sources_active ON discovery_sources(active, priority, source_key);

-- 3. search_terms -------------------------------------------------------------
CREATE TABLE search_terms (
  category TEXT NOT NULL CHECK (category IN ('new_model', 'offer')),
  locale TEXT NOT NULL,
  term TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  priority INTEGER NOT NULL DEFAULT 100 CHECK (priority >= 0),
  added_from TEXT,
  created_at TEXT NOT NULL,
  last_used_at TEXT,
  PRIMARY KEY (category, locale, term)
);
CREATE INDEX idx_search_terms_active ON search_terms(active, priority);

-- 4. search_windows -----------------------------------------------------------
CREATE TABLE search_windows (
  window_key TEXT PRIMARY KEY,
  amount INTEGER NOT NULL CHECK (amount > 0),
  unit TEXT NOT NULL CHECK (unit IN ('hour', 'day')),
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  priority INTEGER NOT NULL DEFAULT 100 CHECK (priority >= 0)
);

-- 5. YAML seed data (AC-13: category and parent structure preserved) ----------
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:openai', 'vendor', 'OpenAI', NULL, NULL, 1, 0, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:anthropic', 'vendor', 'Anthropic', NULL, NULL, 1, 1, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:google-ai-studio', 'vendor', 'Google AI Studio', NULL, NULL, 1, 2, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:google-vertex-ai', 'vendor', 'Google Vertex AI', NULL, NULL, 1, 3, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:xai', 'vendor', 'xAI', NULL, NULL, 1, 4, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:mistral', 'vendor', 'Mistral', NULL, NULL, 1, 5, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:cohere', 'vendor', 'Cohere', NULL, NULL, 1, 6, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:ai21', 'vendor', 'AI21', NULL, NULL, 1, 7, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:meta', 'vendor', 'Meta', NULL, NULL, 1, 8, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:nvidia', 'vendor', 'NVIDIA', NULL, NULL, 1, 9, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:z-ai', 'vendor', 'Z.ai', NULL, NULL, 1, 10, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:bigmodel', 'vendor', 'BigModel', NULL, NULL, 1, 11, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:deepseek', 'vendor', 'DeepSeek', NULL, NULL, 1, 12, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:moonshot-ai', 'vendor', 'Moonshot AI', NULL, NULL, 1, 13, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:kimi', 'vendor', 'Kimi', NULL, NULL, 1, 14, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:minimax', 'vendor', 'MiniMax', NULL, NULL, 1, 15, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:alibaba-cloud-model-studio', 'vendor', 'Alibaba Cloud Model Studio', NULL, NULL, 1, 16, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:dashscope', 'vendor', 'DashScope', NULL, NULL, 1, 17, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:qwen', 'vendor', 'Qwen', NULL, NULL, 1, 18, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:qoder', 'vendor', 'Qoder', NULL, NULL, 1, 19, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:tencent-hunyuan', 'vendor', 'Tencent Hunyuan', NULL, NULL, 1, 20, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:baidu-qianfan', 'vendor', 'Baidu Qianfan', NULL, NULL, 1, 21, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:bytedance-volcengine-ark', 'vendor', 'ByteDance Volcengine Ark', NULL, NULL, 1, 22, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:amazon-bedrock', 'vendor', 'Amazon Bedrock', NULL, NULL, 1, 23, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:microsoft-azure-ai-foundry', 'vendor', 'Microsoft Azure AI Foundry', NULL, NULL, 1, 24, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:github-models', 'vendor', 'GitHub Models', NULL, NULL, 1, 25, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:inclusionai', 'vendor', 'InclusionAI', NULL, NULL, 1, 26, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:stepfun', 'vendor', 'StepFun', NULL, NULL, 1, 27, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('vendor:01-ai', 'vendor', '01.AI', NULL, NULL, 1, 28, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:openrouter', 'router', 'OpenRouter', NULL, NULL, 1, 29, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:tokenrouter', 'router', 'TokenRouter', NULL, NULL, 1, 30, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:requesty', 'router', 'Requesty', NULL, NULL, 1, 31, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:portkey', 'router', 'Portkey', NULL, NULL, 1, 32, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:helicone', 'router', 'Helicone', NULL, NULL, 1, 33, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:unify', 'router', 'Unify', NULL, NULL, 1, 34, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:eden-ai', 'router', 'Eden AI', NULL, NULL, 1, 35, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:ai-ml-api', 'router', 'AI/ML API', NULL, NULL, 1, 36, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:cometapi', 'router', 'CometAPI', NULL, NULL, 1, 37, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:nanogpt', 'router', 'NanoGPT', NULL, NULL, 1, 38, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:chutes', 'router', 'Chutes', NULL, NULL, 1, 39, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:siliconflow', 'router', 'SiliconFlow', NULL, NULL, 1, 40, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('router:zenmux', 'router', 'ZenMux', NULL, NULL, 1, 41, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:together-ai', 'host', 'Together AI', NULL, NULL, 1, 42, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:fireworks-ai', 'host', 'Fireworks AI', NULL, NULL, 1, 43, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:deepinfra', 'host', 'DeepInfra', NULL, NULL, 1, 44, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:groq', 'host', 'Groq', NULL, NULL, 1, 45, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:cerebras', 'host', 'Cerebras', NULL, NULL, 1, 46, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:sambanova', 'host', 'SambaNova', NULL, NULL, 1, 47, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:nebius-ai-studio', 'host', 'Nebius AI Studio', NULL, NULL, 1, 48, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:novita-ai', 'host', 'Novita AI', NULL, NULL, 1, 49, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:hyperbolic', 'host', 'Hyperbolic', NULL, NULL, 1, 50, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:featherless-ai', 'host', 'Featherless AI', NULL, NULL, 1, 51, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:friendliai', 'host', 'FriendliAI', NULL, NULL, 1, 52, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:hugging-face-inference-providers', 'host', 'Hugging Face Inference Providers', NULL, NULL, 1, 53, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:nvidia-nim', 'host', 'NVIDIA NIM', NULL, NULL, 1, 54, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:cloudflare-workers-ai', 'host', 'Cloudflare Workers AI', NULL, NULL, 1, 55, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:replicate', 'host', 'Replicate', NULL, NULL, 1, 56, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:baseten', 'host', 'Baseten', NULL, NULL, 1, 57, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:modal', 'host', 'Modal', NULL, NULL, 1, 58, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:runpod-serverless', 'host', 'RunPod Serverless', NULL, NULL, 1, 59, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:lambda', 'host', 'Lambda', NULL, NULL, 1, 60, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:scaleway-generative-apis', 'host', 'Scaleway Generative APIs', NULL, NULL, 1, 61, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:ovhcloud-ai-endpoints', 'host', 'OVHcloud AI Endpoints', NULL, NULL, 1, 62, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:digitalocean-gradient-ai', 'host', 'DigitalOcean Gradient AI', NULL, NULL, 1, 63, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('host:heroku-models', 'host', 'Heroku Models', NULL, NULL, 1, 64, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:claude-code', 'product', 'Claude Code', NULL, NULL, 1, 65, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:openai-codex', 'product', 'OpenAI Codex', NULL, NULL, 1, 66, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:cursor', 'product', 'Cursor', NULL, NULL, 1, 67, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:github-copilot', 'product', 'GitHub Copilot', NULL, NULL, 1, 68, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:windsurf', 'product', 'Windsurf', NULL, NULL, 1, 69, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:qoder', 'product', 'Qoder', NULL, NULL, 1, 70, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:cline', 'product', 'Cline', NULL, NULL, 1, 71, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:roo-code', 'product', 'Roo Code', NULL, NULL, 1, 72, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:opencode', 'product', 'OpenCode', NULL, NULL, 1, 73, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:kilo-code', 'product', 'Kilo Code', NULL, NULL, 1, 74, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:continue', 'product', 'Continue', NULL, NULL, 1, 75, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:aider', 'product', 'Aider', NULL, NULL, 1, 76, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:devin', 'product', 'Devin', NULL, NULL, 1, 77, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:sourcegraph-cody', 'product', 'Sourcegraph Cody', NULL, NULL, 1, 78, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('product:jetbrains-ai', 'product', 'JetBrains AI', NULL, NULL, 1, 79, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:litellm-providers', 'discovery', 'LiteLLM Providers', NULL, NULL, 1, 80, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:litellm-provider-pull-requests', 'discovery', 'LiteLLM provider pull requests', NULL, NULL, 1, 81, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:openrouter-model-catalog', 'discovery', 'OpenRouter model catalog', NULL, NULL, 1, 82, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:openrouter-provider-pages', 'discovery', 'OpenRouter provider pages', NULL, NULL, 1, 83, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:artificial-analysis', 'discovery', 'Artificial Analysis', NULL, NULL, 1, 84, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:hugging-face-inference-providers', 'discovery', 'Hugging Face Inference Providers', NULL, NULL, 1, 85, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:github-marketplace-models', 'discovery', 'GitHub Marketplace Models', NULL, NULL, 1, 86, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:pricepertoken', 'discovery', 'PricePerToken', NULL, NULL, 1, 87, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:llm-stats', 'discovery', 'LLM-Stats', NULL, NULL, 1, 88, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:getaiperks', 'discovery', 'GetAIPerks', NULL, NULL, 1, 89, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:free-for-dev-ai-section', 'discovery', 'free-for.dev AI section', NULL, NULL, 1, 90, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:awesome-free-llm-apis-repositories', 'discovery', 'awesome-free-llm-apis repositories', NULL, NULL, 1, 91, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('discovery:free-llm-gateway-repositories', 'discovery', 'free-llm-gateway repositories', NULL, NULL, 1, 92, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-localllama', 'community', 'r/LocalLLaMA', NULL, 'reddit', 1, 93, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-llmdevs', 'community', 'r/LLMDevs', NULL, 'reddit', 1, 94, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-openrouter', 'community', 'r/OpenRouter', NULL, 'reddit', 1, 95, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-qwen-ai', 'community', 'r/Qwen_AI', NULL, 'reddit', 1, 96, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-claudecode', 'community', 'r/ClaudeCode', NULL, 'reddit', 1, 97, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-opencodecli', 'community', 'r/opencodeCLI', NULL, 'reddit', 1, 98, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-cline', 'community', 'r/Cline', NULL, 'reddit', 1, 99, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-cursor', 'community', 'r/cursor', NULL, 'reddit', 1, 100, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-selfhosted', 'community', 'r/selfhosted', NULL, 'reddit', 1, 101, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:r-machinelearning', 'community', 'r/MachineLearning', NULL, 'reddit', 1, 102, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:hacker-news', 'community', 'Hacker News', NULL, 'other', 1, 103, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:product-hunt', 'community', 'Product Hunt', NULL, 'other', 1, 104, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:public-discord-announcements', 'community', 'public Discord announcements', NULL, 'other', 1, 105, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:official-x-accounts', 'community', 'official X accounts', NULL, 'other', 1, 106, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:technical-blogs', 'community', 'technical blogs', NULL, 'other', 1, 107, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('community:newsletters', 'community', 'newsletters', NULL, 'other', 1, 108, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:google-for-startups-cloud', 'other', 'Google for Startups Cloud', NULL, NULL, 1, 109, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:microsoft-for-startups-founders-hub', 'other', 'Microsoft for Startups Founders Hub', NULL, NULL, 1, 110, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:aws-activate', 'other', 'AWS Activate', NULL, NULL, 1, 111, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:nvidia-inception', 'other', 'NVIDIA Inception', NULL, NULL, 1, 112, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:cloudflare-for-startups', 'other', 'Cloudflare for Startups', NULL, NULL, 1, 113, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:oracle-for-startups', 'other', 'Oracle for Startups', NULL, NULL, 1, 114, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:digitalocean-hatch', 'other', 'DigitalOcean Hatch', NULL, NULL, 1, 115, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:github-for-startups', 'other', 'GitHub for Startups', NULL, NULL, 1, 116, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:hugging-face-programs', 'other', 'Hugging Face programs', NULL, NULL, 1, 117, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:vendor-student-programs', 'other', 'vendor student programs', NULL, NULL, 1, 118, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:vendor-research-programs', 'other', 'vendor research programs', NULL, NULL, 1, 119, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('other:vendor-accelerator-programs', 'other', 'vendor accelerator programs', NULL, NULL, 1, 120, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('benchmark:huggingface-model-cards', 'benchmark', 'huggingface_model_cards', NULL, NULL, 1, 121, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('benchmark:vendor-technical-blogs', 'benchmark', 'vendor_technical_blogs', NULL, NULL, 1, 122, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('benchmark:official-x-posts', 'benchmark', 'official_x_posts', NULL, NULL, 1, 123, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('benchmark:github-readme-and-reports', 'benchmark', 'github_readme_and_reports', NULL, NULL, 1, 124, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('benchmark:lmmarketcap-com', 'benchmark', 'lmmarketcap.com', NULL, NULL, 1, 125, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('benchmark:openrouter-ai', 'benchmark', 'openrouter.ai', NULL, NULL, 1, 126, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('benchmark:awesomeagents-ai', 'benchmark', 'awesomeagents.ai', NULL, NULL, 1, 127, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('benchmark:artificialanalysis-ai', 'benchmark', 'artificialanalysis.ai', NULL, NULL, 1, 128, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('benchmark:pricepertoken-com', 'benchmark', 'pricepertoken.com', NULL, NULL, 1, 129, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('watchlist:alibaba-qwen-official-x', 'watchlist', 'Alibaba_Qwen official X', NULL, 'qwen', 1, 130, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('watchlist:qwen-ai', 'watchlist', 'qwen.ai', NULL, 'qwen', 1, 131, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('watchlist:qwen-official-blog', 'watchlist', 'Qwen official blog', NULL, 'qwen', 1, 132, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('watchlist:alibaba-cloud-model-studio-home', 'watchlist', 'Alibaba Cloud Model Studio home', NULL, 'qwen', 1, 133, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('watchlist:alibaba-cloud-model-studio-promotions', 'watchlist', 'Alibaba Cloud Model Studio Promotions', NULL, 'qwen', 1, 134, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('watchlist:alibaba-cloud-token-plan', 'watchlist', 'Alibaba Cloud Token Plan', NULL, 'qwen', 1, 135, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('watchlist:alibaba-cloud-newly-released-models', 'watchlist', 'Alibaba Cloud Newly Released Models', NULL, 'qwen', 1, 136, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);
INSERT INTO discovery_sources (source_key, category, label, source_url, parent_label, active, priority, added_from, created_at, last_attempted_at, last_success_at, consecutive_failures) VALUES ('watchlist:qoder-events', 'watchlist', 'Qoder Events', NULL, 'qwen', 1, 137, 'migration:sources.yaml', '2026-08-01T00:00:00.000Z', NULL, NULL, 0);

INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'latest model', 1, 0, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'new model', 1, 1, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'launch', 1, 2, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'preview', 1, 3, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'beta', 1, 4, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'open weight', 1, 5, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'available now', 1, 6, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'pricing', 1, 7, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'promotion', 1, 8, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'event', 1, 9, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'changelog', 1, 10, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'release', 1, 11, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'model added', 1, 12, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'en', 'deprecation', 1, 13, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', '最新モデル', 1, 14, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', '新モデル', 1, 15, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', '提供開始', 1, 16, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', 'プレビュー', 1, 17, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', 'ベータ', 1, 18, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', 'オープンウェイト', 1, 19, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', '価格改定', 1, 20, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', 'キャンペーン', 1, 21, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', 'イベント', 1, 22, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', 'リリース', 1, 23, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'ja', '提供終了', 1, 24, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '最新模型', 1, 25, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '新模型', 1, 26, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '发布', 1, 27, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '预览', 1, 28, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '测试版', 1, 29, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '开源权重', 1, 30, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '上线', 1, 31, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '定价', 1, 32, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '优惠', 1, 33, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '活动', 1, 34, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '更新日志', 1, 35, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('new_model', 'zh', '下线', 1, 36, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'free API', 1, 37, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'free tier', 1, 38, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'free credits', 1, 39, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'launch credits', 1, 40, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'promotion', 1, 41, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'limited time', 1, 42, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'beta access', 1, 43, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'sponsored inference', 1, 44, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'no credit card', 1, 45, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'coupon', 1, 46, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'promo code', 1, 47, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'balance bonus', 1, 48, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'top-up bonus', 1, 49, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', '10x usage', 1, 50, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', '50% off', 1, 51, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', '70% off', 1, 52, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', '80% off', 1, 53, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', '90% off', 1, 54, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', '95% off', 1, 55, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', '98% off', 1, 56, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'off-peak', 1, 57, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'night-time', 1, 58, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', '$0 per million tokens', 1, 59, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'free tokens data sharing', 1, 60, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'training data opt-in credits', 1, 61, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'share data free tokens', 1, 62, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'allow training free quota', 1, 63, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'data contribution free tier', 1, 64, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);
INSERT INTO search_terms (category, locale, term, active, priority, added_from, created_at, last_used_at) VALUES ('offer', 'any', 'free in exchange for data', 1, 65, 'migration:search_queries.yaml', '2026-08-01T00:00:00.000Z', NULL);

INSERT INTO search_windows (window_key, amount, unit, active, priority) VALUES ('24h', 24, 'hour', 1, 0);
INSERT INTO search_windows (window_key, amount, unit, active, priority) VALUES ('72h', 72, 'hour', 1, 1);
INSERT INTO search_windows (window_key, amount, unit, active, priority) VALUES ('30d', 30, 'day', 1, 2);
